In [2]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

#### 1) Create an array containing 4 elements.

In [3]:
name=make_array('Elizabeth','Frakes','Michigan','Blue')

a. Use numpy function to make all elements uppercase.

In [4]:
np.char.upper(name)

array(['ELIZABETH', 'FRAKES', 'MICHIGAN', 'BLUE'], dtype='<U9')

b. Use numpy function to count the letter a in each element.

In [5]:
np.char.count(name, 'a')

array([1, 1, 1, 0])

c. Optional: Find the length of each element.

In [6]:
sizes = []
for i in name:
    sizes.append(len(i))
    
print(sizes)

[9, 6, 8, 4]


#### 2) Create an array containing EVERY OTHER odd number. (1 to 41)

a. Find the sum and products of the array.

In [8]:
my_range=np.arange(1,46,4)
print(my_range)

[ 1  5  9 13 17 21 25 29 33 37 41 45]


In [9]:
np.sum(my_range) # Sum of array.

276

In [10]:
np.prod(my_range) # Product of array.

616159193

b. Take the natural log of each element.

In [11]:
np.log(my_range)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

c. Find difference of adjacent elements.

In [53]:
np.sum(np.diff(my_range))

44