In [5]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

1)

In [20]:
name=make_array('Elizabeth','Frakes','Michigan','Blue')

a.

In [10]:
np.char.upper(name)

array(['ELIZABETH', 'FRAKES', 'MICHIGAN', 'BLUE'], dtype='<U9')

b.

In [15]:
np.char.count(name, 'a')

array([1, 1, 1, 0])

c.

In [29]:
sizes = []
for i in name:
    sizes.append(len(i))
    
print(sizes)

[9, 6, 8, 4]


2)

a.

In [48]:
my_range=np.arange(1,46,4)
print(my_range)

[ 1  5  9 13 17 21 25 29 33 37 41 45]


In [49]:
np.sum(my_range)

276

In [50]:
np.prod(my_range)

616159193

b.

In [51]:
np.log(my_range)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

c.

In [53]:
np.sum(np.diff(my_range))

44